// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTf78BJG8xGigY8g-GHd5KqKCfTBlU18',
    appId: '1:753659295753:web:aee97cb70abfe79bfb20d8',
    messagingSenderId: '753659295753',
    projectId: 'mithodeals-b6e91',
    authDomain: 'mithodeals-b6e91.firebaseapp.com',
    storageBucket: 'mithodeals-b6e91.firebasestorage.app',
    measurementId: 'G-91VEH1H46P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWnTf16eYHfS7Vn1ywZbpZ3ZzRpeCxs4',
    appId: '1:753659295753:android:f707259856b31169fb20d8',
    messagingSenderId: '753659295753',
    projectId: 'mithodeals-b6e91',
    storageBucket: 'mithodeals-b6e91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6mAZd3Aw7zhcMUIz7pkg5wgfMYHHnZk',
    appId: '1:753659295753:ios:aa13595daf3d5f3bfb20d8',
    messagingSenderId: '753659295753',
    projectId: 'mithodeals-b6e91',
    storageBucket: 'mithodeals-b6e91.firebasestorage.app',
    iosBundleId: 'com.example.mithoDeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6mAZd3Aw7zhcMUIz7pkg5wgfMYHHnZk',
    appId: '1:753659295753:ios:aa13595daf3d5f3bfb20d8',
    messagingSenderId: '753659295753',
    projectId: 'mithodeals-b6e91',
    storageBucket: 'mithodeals-b6e91.firebasestorage.app',
    iosBundleId: 'com.example.mithoDeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJTf78BJG8xGigY8g-GHd5KqKCfTBlU18',
    appId: '1:753659295753:web:b33c00e2f808aaa0fb20d8',
    messagingSenderId: '753659295753',
    projectId: 'mithodeals-b6e91',
    authDomain: 'mithodeals-b6e91.firebaseapp.com',
    storageBucket: 'mithodeals-b6e91.firebasestorage.app',
    measurementId: 'G-CXLX3HC4LZ',
  );
}
