import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:mitho_deals/feature/deals/domain/entitiy/deal_entity.dart';
import 'package:mitho_deals/feature/deals/presentation/bloc/deals_bloc.dart';
import 'package:mitho_deals/feature/deals/presentation/bloc/deals_state.dart';
import 'package:mitho_deals/feature/deals/presentation/bloc/deals_event.dart';

class AddDealScreen extends StatefulWidget {
  const AddDealScreen({super.key});

  @override
  State<AddDealScreen> createState() => _AddDealScreenState();
}

class _AddDealScreenState extends State<AddDealScreen> {
  final _formKey = GlobalKey<FormState>();
  final _foodNameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _originalPriceController = TextEditingController();
  final _discountedPriceController = TextEditingController();
  final _portionsController = TextEditingController();
  
  File? _selectedImage;
  DateTime? _pickupStartTime;
  DateTime? _pickupEndTime;

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.gallery);
    if (picked != null) {
      setState(() => _selectedImage = File(picked.path));
    }
  }

  Future<void> _selectDateTime(bool isStart) async {
    final date = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 7)),
    );
    if (date == null) return;

    final time = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (time == null) return;

    final dateTime = DateTime(date.year, date.month, date.day, time.hour, time.minute);
    setState(() {
      if (isStart) {
        _pickupStartTime = dateTime;
      } else {
        _pickupEndTime = dateTime;
      }
    });
  }

  void _submit() {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedImage == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select an image')),
      );
      return;
    }
    if (_pickupStartTime == null || _pickupEndTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please set pickup times')),
      );
      return;
    }

    // Get current vendor ID (you'll need to implement this based on your auth)
    final vendorId = 'current_vendor_id'; // TODO: Get from auth

    final deal = DealEntity(
      id: '', // Will be generated by Supabase
      vendorId: vendorId,
      foodName: _foodNameController.text,
      description: _descriptionController.text,
      originalPrice: double.parse(_originalPriceController.text),
      discountedPrice: double.parse(_discountedPriceController.text),
      availablePortions: int.parse(_portionsController.text),
      pickupStartTime: _pickupStartTime!,
      pickupEndTime: _pickupEndTime!,
      imageUrl: '', // Will be set by repository
      vendorName: '', // TODO: Get from vendor profile
      vendorAddress: '', // TODO: Get from vendor profile
      latitude: 0.0, // TODO: Get from vendor profile
      longitude: 0.0, // TODO: Get from vendor profile
      isAvailable: true,
    );

    context.read<DealsBloc>().add(AddDeal(
      deal: deal,
      imageFile: _selectedImage,
    ));
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<DealsBloc, DealsState>(
      listener: (context, state) {
        state.whenOrNull(
          addDealSuccess: () {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Deal posted successfully!')),
            );
            Navigator.pop(context);
          },
          addDealError: (message) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error: $message')),
            );
          },
        );
      },
      child: Scaffold(
      backgroundColor: const Color(0xFFF9FAFB),
      appBar: AppBar(
        title: Text('Add New Deal', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(24.w),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Image Picker
              _buildImagePicker(),
              SizedBox(height: 24.h),
              
              // Food Name
              _buildTextField(
                controller: _foodNameController,
                label: 'Food Name',
                hint: 'e.g., Momo Platter',
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 16.h),
              
              // Description
              _buildTextField(
                controller: _descriptionController,
                label: 'Description',
                hint: 'Describe the food...',
                maxLines: 3,
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 16.h),
              
              // Prices Row
              Row(
                children: [
                  Expanded(
                    child: _buildTextField(
                      controller: _originalPriceController,
                      label: 'Original Price',
                      hint: 'Rs. 500',
                      keyboardType: TextInputType.number,
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                  ),
                  SizedBox(width: 16.w),
                  Expanded(
                    child: _buildTextField(
                      controller: _discountedPriceController,
                      label: 'Discounted Price',
                      hint: 'Rs. 250',
                      keyboardType: TextInputType.number,
                      validator: (v) => v!.isEmpty ? 'Required' : null,
                    ),
                  ),
                ],
              ),
              SizedBox(height: 16.h),
              
              // Portions
              _buildTextField(
                controller: _portionsController,
                label: 'Available Portions',
                hint: '5',
                keyboardType: TextInputType.number,
                validator: (v) => v!.isEmpty ? 'Required' : null,
              ),
              SizedBox(height: 24.h),
              
              // Pickup Times
              Text('Pickup Time Window', style: GoogleFonts.poppins(fontSize: 16.sp, fontWeight: FontWeight.w600)),
              SizedBox(height: 12.h),
              Row(
                children: [
                  Expanded(
                    child: _buildTimePicker(
                      label: 'Start',
                      time: _pickupStartTime,
                      onTap: () => _selectDateTime(true),
                    ),
                  ),
                  SizedBox(width: 16.w),
                  Expanded(
                    child: _buildTimePicker(
                      label: 'End',
                      time: _pickupEndTime,
                      onTap: () => _selectDateTime(false),
                    ),
                  ),
                ],
              ),
              SizedBox(height: 32.h),
              
              // Submit Button
              SizedBox(
                width: double.infinity,
                height: 56.h,
                child: ElevatedButton(
                  onPressed: _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFFF6B35),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
                  ),
                  child: Text(
                    'Post Deal',
                    style: GoogleFonts.poppins(
                      fontSize: 18.sp,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    ),
  );
}

  Widget _buildImagePicker() {
    return GestureDetector(
      onTap: _pickImage,
      child: Container(
        width: double.infinity,
        height: 200.h,
        decoration: BoxDecoration(
          color: Colors.grey[200],
          borderRadius: BorderRadius.circular(20.r),
          border: Border.all(color: Colors.grey[300]!),
        ),
        child: _selectedImage != null
            ? ClipRRect(
                borderRadius: BorderRadius.circular(20.r),
                child: Image.file(_selectedImage!, fit: BoxFit.cover),
              )
            : Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.add_photo_alternate, size: 48.sp, color: Colors.grey),
                  SizedBox(height: 8.h),
                  Text('Tap to add photo', style: GoogleFonts.poppins(color: Colors.grey)),
                ],
              ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    int maxLines = 1,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: GoogleFonts.poppins(fontSize: 14.sp, fontWeight: FontWeight.w500)),
        SizedBox(height: 8.h),
        TextFormField(
          controller: controller,
          maxLines: maxLines,
          keyboardType: keyboardType,
          validator: validator,
          decoration: InputDecoration(
            hintText: hint,
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12.r),
              borderSide: BorderSide.none,
            ),
            contentPadding: EdgeInsets.symmetric(horizontal: 16.w, vertical: 16.h),
          ),
        ),
      ],
    );
  }

  Widget _buildTimePicker({
    required String label,
    required DateTime? time,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: EdgeInsets.all(16.w),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12.r),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label, style: GoogleFonts.poppins(fontSize: 12.sp, color: Colors.grey)),
            SizedBox(height: 4.h),
            Text(
              time != null ? DateFormat('MMM d, h:mm a').format(time) : 'Select',
              style: GoogleFonts.poppins(fontSize: 16.sp, fontWeight: FontWeight.w600),
            ),
          ],
        ),
      ),
    );
  }
}
